networks:
  dejima_net:
    driver: bridge
    ipam:
      driver: default
services:
  peer-db:
    cap_add:
    - NET_ADMIN
    container_name: Peer-db
    environment:
    - PEER_NAME=Peer<N>
    image: ekayim/dejima-pg
    networks:
      dejima_net: null
    volumes:
    - ./db/postgresql.conf:/etc/postgresql.conf
    - ./db/initialize.sh:/docker-entrypoint-initdb.d/initialize.sh
    - ./db/setup_files:/etc/setup_files
  peer-proxy:
    cap_add:
    - NET_ADMIN
    command: gunicorn -b 0.0.0.0:8000 --threads 85 server:app
    container_name: Peer-proxy
    depends_on:
    - peer-db
    environment:
    - PEER_NAME=Peer<N>
    image: ekayim/dejima-proxy:latest
    networks:
      dejima_net: null
    ports:
    - 8000:8000
    volumes:
    - ./proxy:/code
version: '3'
